### ISSUE TITLE
default_value not working

### ISSUE THREAD

**Issue by bennewton999** [warpdotdev/Warp#1128]
### Describe the bug

```text
I am adding a simple command to change directories and want to add a default value for the argument used for the directory value.  The default value does not display in the command, only the argument's name displays.
```

### To Reproduce

```
---
name: Start Hybris
command: cd {{project_path}} && start
tags:
  - hybris
description: Start Hybris in Debug mode
arguments:
  - name: project_path
    description: Path to the Hybris Project
    default_value: /default_path
source_url: ""
author: 
author_url: ""
shells: []

```

results in:
`cd project_path && start` with project_path highlighted and no mention of the default value.

### Expected behaviour

```text
cd default_path && start

with default_path highlighted so it can be changed if needed.
```

### Screenshots

![CleanShot 2022-04-19 at 16 43 16](https://user-images.githubusercontent.com/458991/164092323-6345713d-8d16-417b-9888-edae67bc1972.png)

### Operating System

MacOS
