### ISSUE TITLE
Save ssh sessions into Launch Configurations

### ISSUE THREAD

**Issue by dannyneira** [warpdotdev/Warp#1866]
### Discord username (optional)

Danny N#2929

### Describe the solution you'd like?

```text
When saving Launch Configurations, Warp doesn't save current ssh sessions. It saves them in the yaml file cwd as "". I think the ability to add/record configurations should include active ssh sessions, possibly via the command - exec option.
```

### Additional context

As a workaround, you can manually enter `ssh user@www.example.com` into the command - exec section of the yaml file.

### How important is this feature to you?

3

**Comment by dannyneira** [comment]
Please +1 this request as it helps us gauge interest. We will post any updates here.

**Comment by f1rstC0de** [comment]
Yes, this is a very important feature, the absence of which makes the daily use of warp difficult. But it will be even cooler if it becomes possible not only to save open ssh sessions in the Launch Configuration, but also to assign them the same credentials once, for the entire group. For example, like this:
```yaml
name: My Dev
windows:
  - tabs:
    - credentionals:
        user: user1
        password: password1
        key: key1
        - layout:
            cwd: ""
        - layout:
            cwd: ""
        - layout:
            cwd: ""
```
This is a very cool feature that makes life much easier for those who work with cluster systems. Perhaps it makes sense to make a separate menu for storing ssh sessions, with the ability to combine into groups like Termius.
