### ISSUE TITLE
Can't use my own shell prompt

### ISSUE THREAD

**Issue by azone** [warpdotdev/Warp#2048]
### Describe the bug

The shell prompt turns empty if I use my own prompt.

### To Reproduce

1. right click on prompt 
2. select "Use my own prompt"

### Screenshots

<img width="372" alt="image" src="https://user-images.githubusercontent.com/164407/199911540-da9da3a9-55a5-4cdd-8610-78b9044ddbb5.png">
<img width="342" alt="image" src="https://user-images.githubusercontent.com/164407/199911582-eae4d3de-aeb5-480a-8f3e-44bc134cc280.png">

prompt on iTerm
<img width="580" alt="image" src="https://user-images.githubusercontent.com/164407/199912080-bea7d92d-bced-4cb8-b43f-3242e5a3f0b8.png">

### OS Version

12.6

### Shell Version

fish, version 3.5.1

### Warp Version

v0.2022.11.01.08.03.stable_00

### Does this block you from using Warp daily?

Yes

**Comment by dannyneira** [comment]
Hi @azone, Thanks for letting us know! We're sorry about this, this is not an ideal experience. 
Unfortunately, we [don't support multi-line or right-sided prompts](https://docs.warp.dev/features/prompt#multi-line-and-right-sided-prompts).

You can disable the multi-line part of your dotfiles ( custom prompt ) just for Warp by using this conditional statement:

```sh

if [[ $TERM_PROGRAM != "WarpTerminal" ]]; then
##### WHAT YOU WANT TO DISABLE FOR WARP - BELOW

# Whatever you want to disable

##### WHAT YOU WANT TO DISABLE FOR WARP - ABOVE
fi

```

We have a list of incompatible tools here: <https://docs.warp.dev/help/known-issues#list-of-incompatible-tools>
And more info on custom prompts here: <https://docs.warp.dev/features/prompt>

**Comment by azone** [comment]
I'm using starship as my terminal prompt, here is the configuration of my `starship.toml`:
```toml
[cmd_duration]
show_milliseconds = true

[git_status]
ahead = "⇡${count}"
diverged = "⇕⇡${ahead_count}⇣${behind_count}"
behind = "⇣${count}"

[time]
disabled = false
format = "[$time]($style) "
time_format = "%T"
```
