### ISSUE TITLE
Workflows should support lists for default arguements

### ISSUE THREAD

**Issue by MarkDPierce** [warpdotdev/Warp#2176]
### Discord username (optional)

Fitz#9422

### Describe the solution you'd like?

It would be awesome if workflows could support a list of default arguments that would also allow autocompletion if the list is >1.

Currently I have created alias' to cut down on having to remember full blown environment names or rarely used names you are always having to look up.

### Is your feature request related to a problem? Please describe.

To help support multiple environments such as Canary deployment methods and similar concepts.

Its frustrating always having to remember specific namespaces or if you work as a freelancer and need to authenticate to multiple clients or environments such as google cloud.

```yaml
---
name: Switch to a different namespace
command: "kubectl config set-context --current --namespace={{namespace}}"
tags:
  - kubectl
description: "Switch to a different namespace"
arguments:
  - name: namespace
    description: The Namespace you want to switch to
    default_values: 
      - default
      - prod-namespace-other-text
      - dev-namespace-other-text
      - test-namespace-other-text
      - canary-namespace-other-text
author: Foo
shells: []
```

Another example, except using gcloud commands
```yaml
---
name: Switch Google Cloud configs and logs in user
command: "gcloud config configurations activate {{env}}"
tags:
  - google
  - gcloud
description: "Switches google cloud configs and auth user"
arguments:
  - name: env
    description: The Gcloud config you want to switch to
    default_values: 
      - work
      - private
      - client1
      - client2
author: Foo
shells: []
```
```


### Additional context

_No response_

### How important is this feature to you?

2

### Warp Internal (ignore) - linear-label:770f6576-d6c0-4e4f-a259-fc64b5156087

_No response_
