### ISSUE TITLE
Launch configuration issue

### ISSUE THREAD

**Issue by beyerss** [warpdotdev/Warp#2282]
### Describe the bug

I have created a launch configuration but when I open launch configuration palette I just see "No matching launch configurations"

### To Reproduce

1. Setup a launch configuration (I just used the command palette to "Save New Launch Configuration"
2. Restart warp
3. open the launch configuration palette

### Expected behaviour

 I would see the available configurations

### Screenshots

Results from the launch configuration palette:
<img width="1016" alt="Screenshot 2022-12-02 at 12 15 57 PM" src="https://user-images.githubusercontent.com/1074621/205359123-00d43eea-3936-47f9-b837-f23c4cf5501a.png">

The configuration is in the proper directory:
<img width="1017" alt="Screenshot 2022-12-02 at 12 16 26 PM" src="https://user-images.githubusercontent.com/1074621/205359207-5f7d79d3-040d-4439-9889-07e81b14b596.png">

Configuration:
<img width="435" alt="Screenshot 2022-12-02 at 12 17 14 PM" src="https://user-images.githubusercontent.com/1074621/205359346-089ee2bd-4fb7-4f73-8af3-7e5117b80e09.png">

### Operating System

MacOS

### OS Version

13.0.1

### Shell Version

zsh 5.8.1

### Warp Version

v0.2022.11.29.08.03.stable_01

### Does this block you from using Warp daily?

No

### Warp Internal (ignore): linear-label:b8107fdf-ba31-488d-b103-d271c89cac3e

None

**Comment by dannyneira** [comment]
Hi @beyerss Sorry about this, can you try with the first two commands in parenthesis? I'm curious if the `.` in the commands is preventing the launch config from showing up.

![CleanShot 2022-12-02 at 11 23 32](https://user-images.githubusercontent.com/16809145/205360793-e9de08ff-5947-49eb-aabc-fb9b5298b584.png)

**Comment by dannyneira** [comment]
@beyerss Any luck with the above? Can we close this issue out or does the issue persist with the parenthesis?

**Comment by natew8** [comment]
Running into this same issue. For me, it seems like adding commands is causing the issue. If I create a launch config without commands it shows in the palette. I tried your suggestion, @dannyneira, and wrapped my commands (the ones with `.` and the ones without) in parenthesis with no luck :/.

**Comment by villagab4** [comment]
Second. This isn't working for me on mac

**Comment by shadowrider17** [comment]
Third. This isn't working for me either. I was trying out this feature for the first time.

**Comment by felixsanz** [comment]
it works if you use parens like @dannyneira said

**Comment by TLMondo** [comment]
I'm having the same issue. Trying with `exec: "..."` and just quotes: `"ssh ..."` doesn't work
As soon as I make ANY modification to the file that is exported with `File` > `Launch Configurations` > `Save New`, then the menu item disappears. Whenever I use the quotes `yamllint` complains that `The line is too long`:

  19:81     error    line too long (81 > 80 characters)  (line-length)
  23:81     error    line too long (81 > 80 characters)  (line-length)


`~/.warp/launch_configurations/META.yaml`

```yaml
# Warp Launch Configuration

---
name: META
windows:
  - tabs:
      - title: META
        layout:
          split_direction: horizontal
          panes:
            cwd: /PATH_TO_PROJECT
            commands:
              - ssh -o 'IdentitiesOnly=yes' -i ~/.ssh/KEY.pem SSH_USER@XXXX
              - sudo docker ps
            split_direction: vertical
            panes:
              - cwd: /PATH_TO_PROJECT
              - commands:
                  - ssh -o 'IdentitiesOnly=yes' -i ~/.ssh/KEY.pem SSH_USER@XXXX
                  - htop
              - cwd: /PATH_TO_PROJECT
              - commands:
                  - ssh -o 'IdentitiesOnly=yes' -i ~/.ssh/KEY.pem SSH_USER@XXXX
                  - tail -f logs/output.log
        color: blue

```

**Comment by dannyneira** [comment]
@TLMondo There are a few potential issues with your yaml file:

1. The commands section needs to use the exec: prefix for each command
2. The indentation of your panes structure is incorrect
3. You should use double quotes for commands with special characters

Try this corrected code (note that the commands after SSH may not run correctly since we `&&` the commands in separate lines)

```yaml
# Warp Launch Configuration

---
name: META
windows:
  - tabs:
      - title: META
        layout:
          split_direction: horizontal
          panes:
            - cwd: /PATH_TO_PROJECT
              commands:
                - exec: "ssh -o 'IdentitiesOnly=yes' -i ~/.ssh/KEY.pem SSH_USER@XXXX"
                - exec: "sudo docker ps"
            - split_direction: vertical
              panes:
                - cwd: /PATH_TO_PROJECT
                  commands:
                    - exec: "ssh -o 'IdentitiesOnly=yes' -i ~/.ssh/KEY.pem SSH_USER@XXXX"
                    - exec: "htop"
                - cwd: /PATH_TO_PROJECT
                  commands:
                    - exec: "ssh -o 'IdentitiesOnly=yes' -i ~/.ssh/KEY.pem SSH_USER@XXXX"
                    - exec: "tail -f logs/output.log"
        color: blue
```
For anyone else with issues, if you're unsure of the Launch Configuration yaml syntax, refer to the examples in our docs and/or "Ask kapa ai" in our docs, this should help correct your syntax. https://docs.warp.dev/features/sessions/launch-configurations
