### ISSUE TITLE
Can't seem to be able to set background image

### ISSUE THREAD

**Issue by ScopeSV** [warpdotdev/Warp#2440]
### Describe the bug

I cant set a background image. Following the guides. Does not work.
I've tried one of the standard downloaded themes (from the git repository in the docs) which had background image commented out. Removed the comments, but no luck there either

```yaml
accent: "#ff047d"
background: "#231b4d"
background_image:
  path: ~/.warp/themes/standard/30012.jpg
details: darker
foreground: "#37dcf6"
terminal_colors:
  bright:
    black: "#1b5689"
    blue: "#4badff"
    cyan: "#37dcf6"
    green: "#7adc03"
    magenta: "#b1a7ff"
    red: "#ff047d"
    white: "#ebe5f2"
    yellow: "#ffeb00"
  normal:
    black: "#1b5689"
    blue: "#4badff"
    cyan: "#37dcf6"
    green: "#7adc03"
    magenta: "#b1a7ff"
    red: "#ff047d"
    white: "#ebe5f2"
    yellow: "#ffeb00"
```

### To Reproduce

Set background image 

### Expected behaviour

Set background image

### Screenshots

![Skjermbilde 2023-01-05 kl  09 46 22](https://user-images.githubusercontent.com/83061036/210738635-149457f3-4074-4db0-8a6f-9898421632a2.png)

### Operating System

None

### OS Version

13.1

### Shell Version

zsh 5.8.1 (arm-apple-darwin21.3.0)

### Warp Version

v0.2022.12.13.08.04.stable_01

### Does this block you from using Warp daily?

Yes, this issue prevents me from using Warp daily.

### Warp Internal (ignore): linear-label:b8107fdf-ba31-488d-b103-d271c89cac3e

None

**Comment by alokedesai** [comment]
Hey @ScopeSV! Sorry for the troubles here. Just to confirm, `~/.warp/themes/standard/30012.jpg` is a valid image in that path, right? Out of curiosity, does this work if you use a relative path instead? See [this theme](https://github.com/warpdotdev/themes/blob/main/warp_bundled/dark_city.yaml) as an example.

**Comment by ScopeSV** [comment]
Yeah I'm 100% sure. And warp terminal even suggested it, so the path works. I tried to do it exactly as the example,  but this invalidated the theme I think. Or at least, it got removed from the list of themes. I also tried to set the exact path, by having the image in the same directory and just doing `path: 30012.jpg`. It didn't work either.

**Comment by alokedesai** [comment]
Would you be able to zip your ~/.warp/themes directory and send it to me at aloke@warp.dev so I can try to reproduce further? Thank you so much!

**Comment by alokedesai** [comment]
I see the issue in the zip you sent--the relative path has to be relative to the parent `~/.warp/themes` directory, which means that it must be the following. Changing this worked for me.

```yaml
accent: "#ff047d"
background: "#231b4d"
background_image:
  path: standard/30012.jpg
details: darker
foreground: "#37dcf6"
terminal_colors:
  bright:
    black: "#1b5689"
    blue: "#4badff"
    cyan: "#37dcf6"
    green: "#7adc03"
    magenta: "#b1a7ff"
    red: "#ff047d"
    white: "#ebe5f2"
    yellow: "#ffeb00"
  normal:
    black: "#1b5689"
    blue: "#4badff"
    cyan: "#37dcf6"
    green: "#7adc03"
    magenta: "#b1a7ff"
    red: "#ff047d"
    white: "#ebe5f2"
    yellow: "#ffeb00"

```

That being said, there does seem to be a bug with absolute paths when using `~`. I'll work on fixing this now, with the hope that it's available in next week's release.
