### ISSUE TITLE
Full Keyboard Access causes input problems with Warp (e.g.: [space key] not working)

### ISSUE THREAD

**Issue by xiaoaiaxss** [warpdotdev/Warp#2734]
### Describe the bug

`when I open a window with launch configure file  blow , I can not press space key, it seems dead. all in one,I can only input a shell command without parameter`
```yaml
name: "test"
windows:
  - tabs:
      - title: test 
        layout:
          cwd: /home/hudson
          commands:
            - exec: ssh hudson@xxx.xxx.xxx.xxx
        color: blue
```

### To Reproduce

`description above`

### Screenshots

![image](https://user-images.githubusercontent.com/18161071/222424893-ebb0b087-4b02-4abe-af59-659dada20d25.png)
`in this picture, I want to input hostname -i but I can't input a blank space key`

### Operating System

MacOS

### OS Version

13.2.1 

### Shell Version

GNU bash, version 3.2.57(1)-release /zsh 5.8.1  remote is  GNU bash, version 4.2.46

### Warp Version

v0.2023.02.21.08.03.stable_01

### Does this block you from using Warp daily?

Yes, this issue prevents me from using Warp daily.

### Warp Internal (ignore): linear-label:b8107fdf-ba31-488d-b103-d271c89cac3e

None
