### ISSUE TITLE
Warp crash on switching tab from launch config with ssh and tmux

### ISSUE THREAD

**Issue by renkun-ken** [warpdotdev/Warp#2766]
### Describe the bug

After upgrading to the latest version (v0.2023.03.07.08.02.stable_01) of Warp, the crash occurs. Before this release, everything works normally.

When I use "Launch Configuration Palette", choose one of the configs as usual, and a new window pop up with a few tabs (each runs a ssh command to different remote servers). If I stay on the initial tab, nothing happens. But if I switch to any other tab, Warp will crash.

It does not crash if I use a simple launch config where a few tabs are defined with only simple `ls` or `ssh` command. But as long as I change the exec command to something like `ssh -t host1 "tmux new -A -s $USER"`, it will crash and is reliably reproducible.

The following is the crash report produced:

[warp-crash-report.log](https://github.com/warpdotdev/Warp/files/10952615/warp-crash-report.log)

### To Reproduce

Put a new launch config in `~/.warp/launch_configurations/test.yaml`, and use the following:

```yaml
---
name: test
windows:
  - tabs:
      - title: test1
        layout:
          cwd: /Users/$USER
          commands:
            - exec: ssh -t host1 "tmux new -A -s $USER" 
      - title: test2
        layout:
          cwd: /Users/$USER
          commands:
            - exec: ssh -t host2 "tmux new -A -s $USER" 
      - title: test3
        layout:
          cwd: /Users/$USER
          commands:
            - exec: ssh -t host3 "tmux new -A -s $USER" 
```

Those `host1`, `host2`, `host3` should be replaced by some accessible servers.

And then:

1. Launch Warp
2. Launch Configuration Palette
3. Choose the config above
4. A new window with 3 tabs will appear.
5. Switch to another tab, the window will crash.

### Expected behaviour

Switching to another tab should not result in a crash

### Operating System

MacOS

### OS Version

13.2.1

### Shell Version

zsh 5.9

### Warp Version

v0.2023.03.07.08.02.stable_01

### Does this block you from using Warp daily?

Yes, this issue prevents me from using Warp daily.

### Warp Internal (ignore): linear-label:b8107fdf-ba31-488d-b103-d271c89cac3e

None
