### ISSUE TITLE
Layout with split to three

### ISSUE THREAD

**Issue by LiranBri** [warpdotdev/Warp#3162]
### Describe the solution you'd like?

Today i'm using itermocil and i'm able to split the screen to two rows and three columns (see screenshot attached).

but with Warp layouts I'm not able to do so (or don't know how).
it blocks me from moving to Warp currently

e.g how the itermocil  yamllooks like:
```
windows:
  - name: platform
    root: /my_path
    layout: 3_columns
    panes:
      - commands:
          - echo pane
        name: "SIDEKIQ"
      - commands:
          - echo pane
        name: "SIDEKIQ-WORKER-2"
      - commands:
          - echo pane
        name: "CONSOLE"
      - commands:
          - start-webpack
        name: "WEBPACK"
      - commands:
          - echo pane
        name: "RAILS-INTERNAL"
      - commands:
          - echo pane
        name: "RAILS"
```

screenshot:
![screenshot](https://i.ibb.co/tBs1Y36/image.png)

P.S
it would be AMAZING to support itermocil formats as well. it would make migration VERY easy for us

### How important is this feature to you?

5 (Can't work without it!)

### Warp Internal (ignore) - linear-label:770f6576-d6c0-4e4f-a259-fc64b5156087

None
