### ISSUE TITLE
Extra newlilne in prompt

### ISSUE THREAD

**Issue by alexdauenhauer** [warpdotdev/Warp#3181]
### Describe the bug

All of the sudden (possible after most recent update?) I have an extra newline in my prompt. There is an extra line between the cursor and the prompt. I am not aware that I have changed antyhing on my settings and this just started. 

### To reproduce

Open warp? not really sure how to reproduce it

### Expected behavior

the cursor would be on the line directly below the prompt as it used to be

### Screenshots

![image](https://github.com/warpdotdev/Warp/assets/11903445/15fa3b60-ac87-4ba3-b212-8077fef612c0)

### Operating system

MacOS

### Operating system and version

13.4 (22F66)

### Shell Version

fish, version 3.6.1

### Current Warp version

v0.2023.05.30.08.03.stable_03

### Regression

Yes, this bug started recently or with an X Warp version

### Recent working Warp date

6/2/2023

### Additional context

here is the relevant parts of my starship.toml file
```toml
format = "$all$fill$jobs$battery$time$status$container$shell$line_break$character"

############# Only use for WARP #############
add_newline = false

[character]
success_symbol = ""
error_symbol = ""
############# Only use for WARP #############
```

### Does this block you from using Warp daily?

No

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

Yes, this I confirmed this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b8107fdf-ba31-488d-b103-d271c89cac3e

None
