### ISSUE TITLE
Invisible `Starship` prompt in `Fish` shell

### ISSUE THREAD

**Issue by danulqua** [warpdotdev/Warp#3362]
### Discord username (optional)

danulqua

### Describe the bug

I use `Starship` prompt with `Fish` shell, and I noticed that my prompt is totally invisible. It becomes visible if I enter new subshells using `fish` or `zsh` commands, and as soon as I exit from them to my main shell, it keeps being invisible.

Demo:

https://github.com/warpdotdev/Warp/assets/38916225/f7272d06-86c2-4fdc-ad7e-c95a72be3541

This problem exists in `Warp` terminal only. In any other terminal everything works fine.
My `Starship` and `Fish` configurations are in the "Additional context" section.

### To reproduce

1. Set up the same environment (`Starship` and `Fish`)
2. Go to `Warp` settings and turn `Honor user's custom prompt (PS1)` on, or right-click the prompt and select `Use my own prompt`
3. Prompt becomes invisible
4. Enter subshell using `fish` command
5. Prompt in the subshell is visible
6. Write `exit` to exit the subshell
7. Prompt in main shell is still invisible

### Expected behavior

`Starship` prompt obviously should be visible all the time.

### Screenshots

![CleanShot 2023-07-13 at 09 35 05@2x](https://github.com/warpdotdev/Warp/assets/38916225/06d2fbad-05a0-4ceb-a260-c07b93e2fef0)

![CleanShot 2023-07-13 at 09 43 31@2x](https://github.com/warpdotdev/Warp/assets/38916225/e37c9df3-8ddd-410d-8cf1-d5eed74bd7d9)

### Operating system

MacOS

### Operating system and version

macOS Ventura 13.4.1

### Shell Version

fish 3.6.1

### Current Warp version

v0.2023.07.04.08.03.stable_02

### Regression

No, this bug or issue has existed throughout my experience using Warp

### Additional context

My `starship.toml`:
```toml
[aws]
style = "bold #FFCA80"

[character]
error_symbol = "[❯](bold #FF9580)"
success_symbol = "[❯](bold #8AFF80)"

[cmd_duration]
style = "bold #FFFF80"

[directory]
style = "bold #8AFF80"

[git_branch]
style = "bold #FF80BF"

[git_status]
style = "bold #FF9580"

[hostname]
style = "bold #9580FF"

[username]
format = "[$user]($style) on "
style_user = "bold #80FFEA"
```

My `fish.config`:
```fish
if status is-interactive
    # Commands to run in interactive sessions can go here
end

set -x PATH /opt/homebrew/bin $PATH
set -Ux HOMEBREW_CASK_OPTS "--no-quarantine"
set -Ux NULLCMD bat

# The Fuck
thefuck --alias | source

# Starship
starship init fish | source
```

### Does this block you from using Warp daily?

Yes, this issue prevents me from using Warp daily.

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

Yes, this I confirmed this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b8107fdf-ba31-488d-b103-d271c89cac3e

None
