### ISSUE TITLE
Enable "Honor user's custom prompt" with Starship looks strange

### ISSUE THREAD

**Issue by tacshi** [warpdotdev/Warp#3446]
### Describe the bug

When "Honor user's custom prompt" is turned on, Starship prompt is not shown as expected, just like this:
<img width="154" alt="image" src="https://github.com/warpdotdev/Warp/assets/9602839/0b33030b-7ff6-488a-9ff0-ebe30f223610">

### To reproduce

1. My starship config:
```toml
add_newline = false
command_timeout = 3000

[character]
success_symbol = "[➜](bold green)"
error_symbol = "[✗](bold red)"

[directory]
truncation_length = 20
truncate_to_repo = true
style = "bold cyan"
format = "[$path]($style)[$read_only]($read_only_style) "
disabled = false

[git_branch]
# symbol = "🌱 "
# truncation_length = 8
# truncation_symbol = "..."
style = "bold purple"
disabled = false

[hostname]
ssh_only = true
# suffix = "⟫"
trim_at = "."
disabled = false

[line_break]
disabled = false

[package]
# symbol = "📦 "
# style = "bold red"
disabled = true

[python]
symbol = "🐍 "
pyenv_version_name = false
pyenv_prefix = "pyenv"
style = "bold yellow"
disabled = false

[docker_context]
disabled = false

[username]
style_root = "bold red"
style_user = "bold yellow"
show_always = false
disabled = false
```
2. Turn on "Honor user's custom prompt

### Expected behavior

The '→ ' should be the same line with cursor, not <dir>/<→ >/<cursor> in different lines, expected look should like this:
<img width="116" alt="image" src="https://github.com/warpdotdev/Warp/assets/9602839/bf35cb43-7eae-47a9-88b7-b4736692527f">

### Screenshots

<img width="154" alt="image" src="https://github.com/warpdotdev/Warp/assets/9602839/498a5b7e-247f-4117-a0bf-4755779f74f2">

### Operating system

MacOS

### Operating system and version

macOS 13.4.1 (c) 

### Regression

No, this bug or issue has existed throughout my experience using Warp

### Does this block you from using Warp daily?

No

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

Yes, this I confirmed this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b8107fdf-ba31-488d-b103-d271c89cac3e

None
