### ISSUE TITLE
overlay for background image

### ISSUE THREAD

**Issue by JasonBoyett** [warpdotdev/Warp#3549]
### Discord username (optional)

JasonB#1857

### Describe the solution you'd like?

```Text
I'd like there to be an option to create an overlay for your background in the configuration for custom themes. In Kitty and other terminal emulators that let you set a background image, you can also set a transparent overly that is displayed on top of that image. This makes it a lot easier to look at the terminal for an extended period of time while still enjoying the aesthetic of having a custom background image. Especially if you're like me and change your background image often.
```

### Additional context

![image](https://github.com/warpdotdev/Warp/assets/93905215/d33eac7d-660c-460a-b7fc-e5ba66718f1c)
this is my terminal in Kitty with the overlay on.

![Screenshot 2023-08-17 at 2 52 57 AM](https://github.com/warpdotdev/Warp/assets/93905215/81f94846-3be7-40b0-b516-d8e896dedd87)
this is the same image as my background in warp

the slightly darker version is just a bit easier to look at for an extended period of time.

### How important is this feature to you?

2

### Warp Internal (ignore) - linear-label:770f6576-d6c0-4e4f-a259-fc64b5156087

None

**Comment by benomzn** [comment]
Yes, I also want this feature

**Comment by benomzn** [comment]
@JasonBoyett Just create a custom terminal, set the background color to #000000 and set the opacity image:

```
---
background: "#000000"
accent: "#1c1e4d"
foreground: "#ffffff"
background_image:
  path: /Users/devnetmind/.warp/themes/sukunaVgojo.jpeg
  opacity: 10
details: darker
terminal_colors:
  normal:
    black: "#616161"
    red: "#ff8272"
    green: "#b4fa72"
    yellow: "#fefdc2"
    blue: "#a5d5fe"
    magenta: "#ff8ffd"
    cyan: "#d0d1fe"
    white: "#f1f1f1"
  bright:
    black: "#8e8e8e"
    red: "#ffc4bd"
    green: "#d6fcb9"
    yellow: "#fefdd5"
    blue: "#c1e3fe"
    magenta: "#ffb1fe"
    cyan: "#e5e6fe"
    white: "#feffff"
name: sukunaVgojo
```

Example of my custom theme with 100 opacity / 0 opacity background image:

<img width="1500" alt="image" src="https://github.com/warpdotdev/Warp/assets/87614390/0eda57da-6bf2-4e1e-a9db-2c086387c1c9">

--

<img width="1500" alt="image" src="https://github.com/warpdotdev/Warp/assets/87614390/d4819f8b-4060-4598-9a51-68c6d2c6ccc7">
