### ISSUE TITLE
"Warpify Subshell" killing docker process

### ISSUE THREAD

**Issue by dj-khite** [warpdotdev/Warp#3615]
### Describe the bug

When connected to a running docker container, "warpify subshell" will crash it

### To reproduce

In tab 1, start a docker container - `docker-compose up`
In tab 2, connect to docker container - `docker exec -it {{container_name}} /bin/bash`
Once successfully connected, click "Warpify Subshell"
Warpification seems successful, and then docker container immediately crashes

### Screenshots

![Kapture 2023-08-31 at 15 57 40](https://github.com/warpdotdev/Warp/assets/131533058/da32a728-8a85-4b07-b0d1-aa89d5e6ca6b)

### Operating system

MacOS

### Operating system and version

Intel Mac; Ventura 13.5.1

### Shell Version

zsh 5.9 (x86_64-apple-darwin22.0)

### Current Warp version

v0.2023.08.29.08.04.stable_00

### Regression

No, this bug or issue has existed throughout my experience using Warp

### Does this block you from using Warp daily?

No

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

N/A, the issue only applies to a Warp specific feature. (i.e. Warp AI, Workflows)

### Warp Internal (ignore): linear-label:b8107fdf-ba31-488d-b103-d271c89cac3e

None

**Comment by dj-khite** [comment]
Apologies for the tiny GIF; kept having to scale down to fit filesize limits. You should at least be able to see that warpifying the subshell on the right immediately kills the docker container on the left. I can reproduce this every time I try it

**Comment by dj-khite** [comment]
Docker version 24.0.2, build cb74dfc

Container is using debian 12.1 and is running a Ruby 3/Rails 7 app. I'm using a `binding.pry_remote` breakpoint in my code that opens a connection on the container to be used for live debugging

I'm running the container with `docker-compose up` and my `docker-compose.yml` file looks like so:

```
version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - ./.env
    ports:
      - "3000:3000"
      - "35729:35729"
      - "9876:9876" # for pry-remote
    volumes:
      - .:/usr/src
    command: ./bin/dev.sh  # This will override the CMD directive from the Dockerfile from staging/prod startup to dev
    depends_on:
      - db
    stdin_open: true
    tty: true

  db:
    image: postgres:14.8-bullseye
    ports:
      - "5432:5432"
    env_file:
      - ./.env
```

Hopefully that's enough info for you, lmk if I missed anything 🙂
