### ISSUE TITLE
Color rendering incorrect in Warp - Tmux, Mutt, Midnight Commander, etc.

### ISSUE THREAD

**Issue by AngerM** [warpdotdev/Warp#362]
### Describe the bug

The color rendering of tmux in warp seems to not be properly setting colors. The same settings work fine in iterm2 or alacritty.

example .tmux.conf:
```
set -g status on
set -g status-interval 2
set -g status-fg colour231
set -g status-bg colour234
set -g status-left-length 20
set -g status-left '#[fg=green,bg=colour234,nobold] #(whoami)  '
set -g status-right "#[fg=yellow] %d %b %Y #[fg=green]:: %l:%M %p"
set -g status-right-length 150
set -g window-status-format "#[fg=colour234,bg=colour234]#[fg=colour244,bg=colour234](#I)#[default] #W #[fg=colour234,bg=colour234]"
set -g window-status-current-format "#[fg=colour4,bg=colour234]#[fg=colour0,bg=colour4](#I) #W #[fg=colour4,bg=colour234,nobold]"
```

### To Reproduce

use the above settings in tmux, and start a session. 

### Expected behaviour

Colors should be rendered correctly

### Screenshots

Warp's rendering:
![image](https://user-images.githubusercontent.com/1715525/140564898-fb7c3242-ecd4-4e1f-ba28-82f88701e6f5.png)

Alacritty rendering:
![image](https://user-images.githubusercontent.com/1715525/140564984-db7d8a99-30ee-47dc-b0de-2889e44df683.png)

### Operating System

MacOS

### OS Version

11.6.1

### Additional context

```shell
~ tmux -V
tmux 3.2a
~ zsh --version
zsh 5.8 (x86_64-apple-darwin19.6.0)
```
```

**Comment by elviskahoro** [comment]
Hey! I think the underlying issue is that we added support for enforcing contrast but should put it behind a toggle. Idk when the toggle will come out though tbh

**Comment by elviskahoro** [comment]
From #453 via @xorik
### Describe the bug

```shell
No colors in midnight commander (mc in brew)
```


### To Reproduce

Steps to reproduce:
1. Open `mc`

### Expected behaviour

```shell
Files and folders has colors
```


### Screenshots

Warp VS iterm2
![Screen Shot 2021-11-22 at 22 01 07](https://user-images.githubusercontent.com/347044/142934816-a861b7f3-34ef-4f9b-94df-a624c55f856c.png)


### Operating System

MacOS

### OS Version

12.0

### Additional context

_No response_

**Comment by elviskahoro** [comment]
From #837 via @ttunguz
### Describe the bug

```text
- pick a standard color scheme in mutt
- pick a standard color scheme in warp
- compare mutt colors in Terminal.app and Warp; they will be different in unexpected ways
```


### To Reproduce

- pick a standard color scheme in mutt
- pick a standard color scheme in warp
- compare mutt colors in Terminal.app and Warp; they will be different in unexpected ways


### Expected behaviour

```text
The color scheme in mutt should reflect the .muttrc configuration
```


### Screenshots

<img width="1297" alt="Screen Shot 2022-03-24 at 11 29 58" src="https://user-images.githubusercontent.com/458598/159952249-f8dafac5-494c-487e-bec5-46868af86179.png">
<img width="1303" alt="Screen Shot 2022-03-24 at 11 28 40" src="https://user-images.githubusercontent.com/458598/159952251-41054bcc-3850-4644-aba5-b879530fbded.png">


### Operating System

MacOS

### OS Version

12.2.1

### Additional context

_No response_

**Comment by elviskahoro** [comment]
From #1835 via @buesing
### Discord username (optional)

_No response_

### Describe the bug

Compare this (warp):
<img width="988" alt="image" src="https://user-images.githubusercontent.com/1181371/190447698-67131c52-9e4a-401a-bbf5-7a37ef4981e9.png">

To this (iTerm2):
<img width="880" alt="image" src="https://user-images.githubusercontent.com/1181371/190447752-a57dced2-d572-4ac9-a51b-155fdb960be4.png">

Some colors seem to be switched around in the solarized color scheme. What's normally grey is white in warp, and vice versa, other colors are changed too. I don't mind putting a spin on color schemes but solarized specifically has been popular due to it's precision, so I think it should be used as-is.
In my example what is specifically questionable is that the comments are a lighter shade than the actual code, which is confusing in terms of visual hierarchy.

Another example from within zsh:
warp:
<img width="650" alt="image" src="https://user-images.githubusercontent.com/1181371/190451414-41a0936c-04dd-4112-840c-005d6cc78d42.png">

iterm2:
<img width="726" alt="image" src="https://user-images.githubusercontent.com/1181371/190451477-14a48383-c97f-4a4e-9aeb-60d6a3e80093.png">

Terminal.app
<img width="670" alt="image" src="https://user-images.githubusercontent.com/1181371/190451535-af392545-2b16-4ff7-b25f-0503ade8b48e.png">


### To Reproduce

Open warp with solarized dark, observe a different color scheme than in other terminal emulators.

### Expected behaviour

_No response_

### Screenshots

_No response_

### Operating System

MacOS

### OS Version

12.0

### Shell Version

zsh 5.8

### Warp Version

v0.2022.09.07.14.56.stable_00

### Additional context

_No response_

### Does this block you from using Warp daily?

No

### Warp Internal (ignore): linear-label:b8107fdf-ba31-488d-b103-d271c89cac3e

_No response_

**Comment by elviskahoro** [comment]
Sharing this across various color related issues. The team fixed one of the core issues with colors and there's a new toggle under Settings > Appearance that let's you configure whether to enforce a minimum contrast (one of the issues). Please check if you're still having color issues again and test tweaking the toggle:

<img width="505" alt="CleanShot 2022-11-10 at 15 17 22@2x" src="https://user-images.githubusercontent.com/29553206/201227106-64005c9c-cbab-446b-84c6-665b80205000.png">

**Comment by rive-n** [comment]
This is not fixed.

**Comment by dannyneira** [comment]
Thanks for the heads up @rive-n, can you please post a copy of your theme .yml file, we don't need the background image.

**Comment by rive-n** [comment]
> Thanks for the heads up @rive-n, can you please post a copy of your theme .yml file, we don't need the background image.

Sure thing! 

```
details: "lighter"
############################################################### SEE BELOW
background_image:
  path: .warp/themes/cyberpunk.JPG
  opacity: 30
############################################################### SEE ABOVE

terminal_colors:
  normal:
    black: "#000000"
    cyan: "#d0d1fe"
    blue: "#a5d5fe"
    white: "#ffffff"
    yellow: "#c2c2c2"
    green: "#e67018"
    red: "#ff705d"
    magenta: "#cacaca"
  bright:
    yellow: "#fefdd5"
    red: "#ffc4bd"
    blue: "#c1e3fe"
    green: "#d6fcb9"
    black: "#555555"
    cyan: "#e5e6fe"
    magenta: "#ffb1fe"
    white: "#ffffff"
accent: "#6959ff"
foreground: "#ffffff"
background: "#000000"
```
