### ISSUE TITLE
Documentation of the full yaml spec of the launch config

### ISSUE THREAD

**Issue by jodybro** [warpdotdev/Warp#3856]
### Describe the solution you'd like?

```Text
The saved config that I generated barely has anything in it. Would be lovely it when saving the config, all the default values are templated out as well.

Also a wiki page showing the full spec would be nice.
```

### Is your feature request related to a problem? Please describe.

```Text
Let me preface this by saying that I absolutely love warp and I hope it keeps on getting better as time goes by (cant wait for the windows version).

If I'm looking in the wrong place then please someone point me to this and I'll hang my head in shame but......I cannot find a single kb article/SO post/wiki page...nothing showing the full spec of the launch config file.

Before I go into a config, I like to look at the spec beforehand to get an idea of what I'd like to change without even knowing about the feature/ability in the tool I'm looking at.
```

### How important is this feature to you?

4

### Warp Internal (ignore) - linear-label:770f6576-d6c0-4e4f-a259-fc64b5156087

None

**Comment by dannyneira** [comment]
Thanks for this feature request @jodybro, We have a number of [examples in our docs for Launch configurations](https://docs.warp.dev/features/sessions/launch-configurations#yaml-format), but I see how one within a new launch config could be helpful as well. 

To anyone else interested in this feature, please add a :+1: to the original post at the top to signal that you want this feature, and subscribe if you'd like to be notified.

**Comment by dannyneira** [comment]
Closing this one as the launch config specs are in the documentation listed above. But please feel free to let us know if there are any issues or questions with setting up new launch configurations.

**Comment by webrgp** [comment]
Let me add that, without a full spec of existing config options, we are limited to the options demonstrated in the doc examples. I wanted to know, for example, if the `commands` option only take `exec`, or do we have other options?

**Comment by dannyneira** [comment]
`exec` is the only option for commands, but you can chain commands with `;` or just have different `exec` lines if you want them to run in parallel ( similar to using `&&` between command )

Please see my example of this below:
```
---
name: Release
windows:
  - tabs:
      - title: DX
        layout:
          cwd: /Users/danny/Documents/dx
          commands:
            - exec: git checkout main ; git pull ; code .
      - title: Channel Versions
        layout:
          cwd: /Users/danny/Documents/dx/src/channel-versions
          commands:
            - exec: git checkout main ; git pull ; open https://docs.google.com/spreadsheets/d/1ua2mKOlJ3VF0S-MrwR_lgdfU0uVcW08EcFVxQcs9uKk/edit#gid=0 ; open https://github.com/warpdotdev/warp-internal/releases ; open https://github.com/warpdotdev/warp-internal/actions
      - title: Gitbook
        layout:
          cwd: /Users/danny/Documents/dx/src/gitbook
          commands:
            - exec: git checkout main ; git pull
```
