### ISSUE TITLE
Custom themes not showing up, ever

### ISSUE THREAD

**Issue by dweslynch** [warpdotdev/Warp#3884]
### Discord username (optional)

Aetalix

### Describe the bug

I've added custom themes to the ~/.warp/themes directory, but they are not showing up in the theme selector in Warp. It's been like this for months.

### To reproduce

I'm not sure how to reproduce this, since for other people it works fine

### Expected behavior

The custom themes I've added appear in the theme selector

### Screenshots

<img width="1006" alt="Screenshot 2023-11-17 at 2 10 58 PM" src="https://github.com/warpdotdev/Warp/assets/32858150/003cd163-e364-4c0f-9806-a3f8c44fc0f0">

### Operating system

MacOS

### Operating system and version

MacOS Ventura 13.4.1

### Shell Version

zsh 5.9 (x86_64-apple-darwin22.0)

### Current Warp version

v0.2023.11.14.08.02.stable_02

### Regression

No, this bug or issue has existed throughout my experience using Warp

### Recent working Warp date

Has never worked for me

### Does this block you from using Warp daily?

No

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

Yes, this I confirmed this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b8107fdf-ba31-488d-b103-d271c89cac3e

None

**Comment by dannyneira** [comment]
Hey @dweslynch, please check and make sure your permissions are similar to mine for those folders, and try and restart Warp to see if it shows up. If that doesn't help, please post a copy of the theme on this thread, and we can try to reproduce the issue.

![CleanShot 2023-11-17 at 16 43 58](https://github.com/warpdotdev/Warp/assets/16809145/b2a8fe9d-1413-4385-ad10-86e9c11ade8f)

**Comment by dannyneira** [comment]
@dweslynch any luck with the above?

**Comment by jvantuyl** [comment]
Looks like it's failing to parse your YAML and doesn't really indicate that anywhere.

Specifically, look at `terminal_colors` -> `light` -> `cyan`.  Notice the space after the color?  When I remove that, the theme loads for me.

**Comment by moooooo16** [comment]
You can't use capital letter. 
In my case I change all to lower case, and it worked.

**Comment by lightify97** [comment]
I had the same issue on Linux (Ubuntu). Placing the theme in ~/.warp/themes didn't work. But copying the same to ~/.local/share/warp-terminal/themes worked.

**Comment by jcnmsg** [comment]
> I had the same issue on Linux (Ubuntu). Placing the theme in ~/.warp/themes didn't work. But copying the same to ~/.local/share/warp-terminal/themes worked.

Same thing on Linux Mint.

**Comment by timohermans** [comment]
> I had the same issue on Linux (Ubuntu). Placing the theme in ~/.warp/themes didn't work. But copying the same to ~/.local/share/warp-terminal/themes worked.

Same on Fedora 41

**Comment by dannyneira** [comment]
Hey folks,  you're correct the locations are different for Mac and Linux. Please see below and/or in our docs for details. https://docs.warp.dev/appearance/custom-themes#how-do-i-use-a-custom-theme-in-warp

Custom theme locations:
- macOS: `$HOME/.warp/themes/`
- Linux: `mkdir -p ${XDG_DATA_HOME:-$HOME/.local/share}/warp-terminal/themes/`

Hope this helps! @dweslynch are you still seeing the issue you noted originally?

**Comment by timohermans** [comment]
@dannyneira Thanks Danny, that worked! I took a double take on the docs and immediately found the tab with "linux", saying what you had to do. Stupid I missed that before 🤔

**Comment by dannyneira** [comment]
No worries, it's easy to skim docs, maybe we can have a better UX around auto-switching the tabs per OS since the docs default to the first tab (macOS).

**Comment by dotnetemmanuel** [comment]
What about on Windows?

**Comment by andig** [comment]
Same problem here. Can't get https://github.com/GrimLink/warp-theme-snazzy to show up on Mac:

```yaml
details: darker
accent: "#ff6ac1"
background: "#282a36"
foreground: "#eff0eb"
terminal_colors:
  bright:
    black: "#686868"
    blue: "#57c7ff"
    cyan: "#9aedfe"
    green: "#5af78e"
    magenta: "#ff6ac1"
    red: "#ff5c57"
    white: "#eff0eb"
    yellow: "#f3f99d"
  normal:
    black: "#282a36"
    blue: "#57c7ff"
    cyan: "#9aedfe"
    green: "#5af78e"
    magenta: "#ff6ac1"
    red: "#ff5c57"
    white: "#f1f1f0"
    yellow: "#f3f99d"
```

It would be really nice if Warp raised or logged a proper error message...
