### ISSUE TITLE
zsh shell doesn't load

### ISSUE THREAD

**Issue by MarcBickel** [warpdotdev/Warp#4074]
### Describe the bug

In two situations, the message "starting zsh..." stays on the screen, and no command can be entered. The warming "seems like your shell is taking a while to start comes in". No useful information has been found on that link. Outside these two situations, zsh loads fine (such as opening a new tab or window)
The two situations are: 
- when running a custom workflow which opens 3 tabs and cds into a folder (nothing else). The cd doesn't even happen, so it's zsh that can't be loaded. 
- When opening warp again after it has been closed, with multiple or only one tab. 

This means I always have to close whatever tab I had, and open a new one. Or that custom workflows don't work. 

### To reproduce

1. Install warp on macOS 14.2.1 (M2 macbook), use zsh. 
2. Open warp, cd in a couple of folders, open a couple of tabs. 
3. Close warp with cmd+Q
4. Open warp again and get the "starting zsh..." message staying forever

### Expected behavior

The message goes away after a couple of seconds, and the warp tab is usable. Or, that the workflow works. 

### Screenshots

<img width="1020" alt="Screenshot 2024-01-16 at 10 55 55" src="https://github.com/warpdotdev/Warp/assets/13186695/6526e2dd-def8-472c-9ccb-8ee519c7fe93">

### Operating system

MacOS

### Operating system and version

14.2.1

### Shell Version

zsh 5.9 (x86_64-apple-darwin23.0)

### Current Warp version

v0.2024.01.09.08.02.stable_02

### Regression

No, this bug or issue has existed throughout my experience using Warp

### Does this block you from using Warp daily?

Yes, this issue prevents me from using Warp daily.

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

Yes, this I confirmed this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b9d78064-c89e-4973-b153-5178a31ee54e

None

**Comment by dannyneira** [comment]
Hey @MarcBickel sorry to hear about this blocker. You may have one or more version of zsh installed, I suggest you run `which zsh` and then put the result into Warp > Settings > Features > Sessions > Startup shell for new sessions. This way, your Warp will always try and open the primary/default version of zsh. In my example below it was `/opt/homebrew/bin/zsh`, but yours may be different.

![CleanShot 2024-01-16 at 16 11 00](https://github.com/warpdotdev/Warp/assets/16809145/85789cab-b7fb-4e8a-91ad-2a1ed6e0ebf3)

Please let me know if this helped with your issue loading zsh.

**Comment by MarcBickel** [comment]
Hi @dannyneira, thanks for your answer 😄 Unfortunately that's not it, I only have one version of zsh intalled, `/bin/zsh`. It is also detected fine when I manually select zsh as startup shell (not default and not custom). 

Just to reiterate, when I just open a new tab in an already existing window/session (with cmd+t), then the zsh shell gets loaded up completely fine. This bug really only happens in the two situations I describe in my initial post. All the others use cases are fine (from the solution you describe no use case should have worked, from what I understand?). 

Let me know if I can provide more information, would be glad to do so

PS: I see that I said workflow in my first post, but I meant launch configuration, sorry about that.

**Comment by MarcBickel** [comment]
Here are the content of the launch configuration file: 
```
# Warp Launch Configuration
#
#
# Use this to start a certain configuration of windows, tabs, and panes
# Open the launch configuration palette to access and open any launch configuration
#
# This file defines your launch configuration
# More on how to do so here:
# https://docs.warp.dev/features/session-management/launch-configurations
#
# All launch configurations are stored under ~/.warp/launch_configurations/
# Edit them anytime!
#
# You can also add commands that run on-start for your launch configurations like so:
# ---
# name: Example with Command
# windows:
#  - tabs:
#      - layout:
#          cwd: /Users/warp-user/project
#          commands:
#            - exec: code .

---
name: Smart Contract Dev
windows:
  - tabs:
      - layout:
          cwd: /Users/marc/Documents/fume-smart-contracts
      - layout:
          cwd: /Users/marc/Documents/fume-smart-contracts
      - layout:
          cwd: /Users/marc/Documents/fume-smart-contracts
```
