### ISSUE TITLE
Built-in wal theme

### ISSUE THREAD

**Issue by macccorehenni** [warpdotdev/Warp#4231]
### Discord username (optional)

maccorehenni#0

### Describe the solution you'd like?

Wal supports YAML, so it wouldn’t be much of a stretch to use it as a built in theme, or at least provide a Linux command-line option to warp-terminal that’ll allow theming. 

### Is your feature request related to a problem? Please describe.

No.

### Additional context

https://github.com/dylanaraps/pywal 

### How important is this feature to you?

3

### Warp Internal (ignore) - linear-label:39cc6478-1249-4ee7-950b-c428edfeecd1

None

**Comment by Almamu** [comment]
Creating a pywal theme for warp is not that hard. Sadly warp doesn't reload the theme if it changes, so it will only work when starting up the terminal. This is the theme i use with pywal, just symlink it under the warp themes folder to .cache/wal/warp-terminal.yaml and it should work:
```
background: "{background}"
background_image:
  path: {wallpaper}
  opacity: 40
accent:
  left: "{color0}"
  right: "{color1}"
foreground: "{foreground}"
details: darker
terminal_colors:
  normal:
    black: "#616161"
    red: "#ff8272"
    green: "#b4fa72"
    yellow: "#fefdc2"
    blue: "#a5d5fe"
    magenta: "#ff8ffd"
    cyan: "#d0d1fe"
    white: "#f1f1f1"
  bright:
    black: "#8e8e8e"
    red: "#ffc4bd"
    green: "#d6fcb9"
    yellow: "#fefdd5"
    blue: "#c1e3fe"
    magenta: "#ffb1fe"
    cyan: "#e5e6fe"
    white: "#feffff"
```
