### ISSUE TITLE
Colors in terminal

### ISSUE THREAD

**Issue by iwex** [warpdotdev/Warp#4565]
### Describe the bug

I've converted this theme https://github.com/ahmadawais/Shades-of-Purple-iTerm2/blob/master/shades-of-purple.itermcolors with https://terminal-themes.com/create-theme.

And I can't get the same bright colors. Even white is not white. Compared to iterm2 it is a bit darker

![CleanShot 2024-03-15 at 10 48 27](https://github.com/warpdotdev/Warp/assets/4510068/d7e80f11-5ce5-4278-8a96-d4a6fc80ecbd)

Here is the code for it 
```yaml
accent: "#fad000"
background: "#1e1d40"
foreground: "#feffff"
details: "darker"
terminal_colors:
  normal:
    black: "#000000"
    red: "#d90429"
    green: "#3ad900"
    yellow: "#ffe700"
    blue: "#6943ff"
    magenta: "#ff2b70"
    cyan: "#00c5c7"
    white: "#c7c7c7"
  bright:
    black: "#676767"
    red: "#f9291b"
    green: "#42d425"
    yellow: "#f1d000"
    blue: "#6871ff"
    magenta: "#ff76ff"
    cyan: "#79e7fa"
    white: "#feffff"
```

### To reproduce

I've converted this theme https://github.com/ahmadawais/Shades-of-Purple-iTerm2/blob/master/shades-of-purple.itermcolors with https://terminal-themes.com/create-theme and installed to Warp

### Expected behavior

Bright colors

### Screenshots

![CleanShot 2024-03-15 at 10 52 12](https://github.com/warpdotdev/Warp/assets/4510068/91e3a7c4-49a5-4481-82e3-5406f9d5daf1)

### Operating system

MacOS

### Operating system and version

MacOS 14.4

### Shell Version

zsh 5.9

### Current Warp version

v0.2024.03.12.08.02.stable_01

### Regression

No, this bug or issue has existed throughout my experience using Warp

### Does this block you from using Warp daily?

Yes, this issue prevents me from using Warp daily.

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

Yes, this I confirmed this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b9d78064-c89e-4973-b153-5178a31ee54e

None

**Comment by dannyneira** [comment]
Hi @iwex sorry about this, Warp does take into account the details "darker" "lighter" and adds a filter over colors based on that so try swaping to the latter and see if that helps with getting a brighter white. Also make sure you have the same font configured as the font may also be affecting the look of it.

Hope this helps!

**Comment by iwex** [comment]
@dannyneira 
I copied old theme to shades-lighter and replaces darker with lighter, but as you can see - no changes.

https://github.com/warpdotdev/Warp/assets/4510068/8815780c-4f97-4895-83dd-727604fccc50

**Comment by dannyneira** [comment]
Thanks for letting us know. We're looking into the dimming that's being placed on text and will post updates on this thread

**Comment by david-zamora-minderest** [comment]
I have found that in comparison with other terminals, Warp paints what seems to be the blue color as purple. I use Warp with ZSH and starship with a very clean and simple configuration. I tried Ubuntu terminal and Tillix, both paint it dark blue, nor purple.
Tillix / Terminal
![image](https://github.com/warpdotdev/Warp/assets/95277922/ae1154a8-8eac-430d-994e-58bf4b7c7d08)

Warp Image
![image](https://github.com/warpdotdev/Warp/assets/95277922/896e5dc5-d0d4-43d2-86ff-e1c6f2e16906)

**Comment by jennso** [comment]
Having the same issue here I copied my iterm colors theme, I believe the colors are corrrect but seems like warp add a dark overlay or dimms the colors down, maybe is a configurable setting that affects all themes? here is the example.

![image](https://github.com/warpdotdev/Warp/assets/61991816/8dabde6d-e7a1-42f9-b3f3-78ce1dff8757)

**Comment by azat-io** [comment]
I have the same problem. All the colors seem dull.
My theme:

```yaml
accent: "#fabd2f"
background: "#141718"
details: lighter
foreground: "#fbf1c7"
terminal_colors:
  bright:
    black: "#1d2021"
    blue: "#83a598"
    cyan: "#8ec07c"
    green: "#b8bb26"
    magenta: "#d3869b"
    red: "#fb4934"
    white: "#fbf1c7"
    yellow: "#fabd2f"
  normal:
    black: "#1d2021"
    blue: "#458588"
    cyan: "#8ec07c"
    green: "#b8bb26"
    magenta: "#d3869b"
    red: "#fb4934"
    white: "#fbf1c7"
    yellow: "#fabd2f"
```
