### ISSUE TITLE
Workflows - Allow argument to default to another argument

### ISSUE THREAD

**Issue by JoshRiser** [warpdotdev/Warp#4751]
### Describe the solution you'd like?

This may be so unnecessary but something I would like personally for Workflows is the ability for an argument's default value to start of as the value of another argument... Here's what I mean.

I created a workflow that runs multiple commands to install WordPress in a specific folder (truncated the commands for demonstration purposes):
```
---
name: Install WordPress in Folder
command: "mkdir {{folder}}; cd {{folder}}; wp core download; wp core config --dbname={{folder}};"
tags: []
description: ~
arguments:
  - name: folder
    description: Folder name to install to.
    default_value: wordpress
source_url: ~
author: ~
author_url: ~
shells: []
```

I have the argument {{folder}} to enter the folder name to create and install WP into, and currently I am just using the folder name as the database name as well.

I would be great if I could have the database name be an argument as well, but have it default to the folder name argument in case I do in fact want the folder name and database name to be the same.

I suppose it could look something like this:
```
---
name: Install WordPress in Folder
command: "mkdir {{folder}}; cd {{folder}}; wp core download; wp core config --dbname={{db_name}};"
tags: []
description: ~
arguments:
  - name: folder
    description: Folder name to install to.
    default_value: wordpress
  - name: db_name
    description: The name of the database to create.
    default_value: $folder
source_url: ~
author: ~
author_url: ~
shells: []
```

Not sure if it makes more sense for the default value to use the same curly bracket format or be a $ style variable.

### How important is this feature to you?

1 (Not too important)

### Warp Internal (ignore) - linear-label:39cc6478-1249-4ee7-950b-c428edfeecd1

None
