### ISSUE TITLE
Unable to move cursor back to second line after latest update (using Starship)

### ISSUE THREAD

**Issue by onecrayon** [warpdotdev/Warp#5052]
### Dupe Check

- [X] I have [searched Warp bugs](https://github.com/warpdotdev/warp/issues?q=is%3Aissue+label%3ABugs) and there are no duplicates

### Describe the bug

The latest update introduced cursors on the same line as the prompt, which I hate. I'm using a custom cursor, though, so I figured I would just follow the recommended way to adjust to a second line, but it doesn't work.

### To reproduce

1. Install Starship
2. Configure prompt to use Starship with the Warp-recommended follow-up to overwrite the PS1 in `~/.bash_profile`:
    ```sh
    eval "$(starship init bash)"
    PS1="${PS1}"$'\\n'
    ```
3. Restart Warp and the cursor is still on the same line as the Starship prompt

### Expected behavior

There should be a single setting for Warp-provided prompts for same-line cursors that also applies to custom prompts. Maybe Starship is doing something funky, but it's bizarre to me that before Warp just always stuck the cursor on a new line and now it always sticks it on the same line without being able to adjust the behavior in the app.

### Operating system

MacOS

### Operating system and version

14.2

### Shell Version

bash 5.2.15(1)

### Current Warp version

v0.2024.06.18.08.02.stable_03

### Regression

Yes, this bug started recently or with an X Warp version

### Does this block you from using Warp daily?

Yes, this issue prevents me from using Warp daily.

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

Yes, this I confirmed this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b9d78064-c89e-4973-b153-5178a31ee54e

None

**Comment by dannyneira** [comment]
Hi @onecrayon Sorry to hear about this. You may be able to fixed this by putting the following in your ~/.config/starship.toml file.

```
[line_break]
disabled = false
```

You may also need to add the `$line_break` to your file depending on your format string.

If this doesn't help please share your starship.toml file and we will try and reproduce the issue on our end. https://starship.rs/config/#prompt.

Then I recommend removing the `PS1="${PS1}"$'\\n'` from your bashrc file. Also I'm not sure where you saw that recommended. It's typically best to modify the prompt in the starship.toml file.

**Comment by Advait-M** [comment]
Hey @onecrayon 

Thanks for reporting this!

So, first off - to address how to return to the prior state:
- The provided command generally applied to "vanilla" prompts rather than custom prompt plugins, such as Starship, which generally have their own configurations. 
- I checked the command myself against Zsh and Bash's Starship. Verified it actually _does_ work in Zsh, however, it does _not_ work in Bash (due to differences in how the shells pass around their prompts I believe). This command was largely meant to tackle the "simple prompt" case of something like `PS1="foo"`.
- **Could you please provide your `starship.toml`?** I can help with modifying it to revert to the previous behavior. More generally, `add_newline` is the Starship config option for adding a newline or not (see https://starship.rs/config/#options). Feel free to let me know if you'd like to email it to me instead and I can follow up with that (to avoid posting here)!


With respect to Warp's updating behavior:
- The behavior for PS1s within Warp was actually a broken experience. We were not respecting user's custom prompts. We were artificially adding a "newline" at the end of their prompts in Warp.
- We've received a lot of feedback about this being an issue at #2304.
- Hence, we'd made the decision to fix this behavior within Warp and truly respect your PS1/custom prompt. However, we wanted to make it easy for folks to revert their experience if they'd wanted to, hence offering a command to help (in the simple cases). 

Why did we not offer an option within the app to revert the behavior?
- This was a major refactor of core Warp code to support this feature. At a high-level, there'd be a lot of product and tech debt for us to maintain a setting like this within Warp. At the end of the day, the existing PS1 experience within Warp was broken, and this is what it should've been from the start. We do realize the friction it causes folks that want to have the legacy experience, hence our efforts to alleviate this.

That being said, we really appreciate your feedback here - please keep it coming!

**Comment by onecrayon** [comment]
@Advait-M The vast majority of my `starship.toml` is just disabling a bunch of output that I don't want to see, along with custom symbols using a nerd font for some of the formatting for other sub-commands. If you remove all of that, it boils down to just this:

```toml
[line_break]
disabled = true
```

`add_newline` is `true` by default, and I didn't override that (plus I would expect this to have no impact either way, because it has to do with adding newlines *before* the prompt, not after it). However, before filing this issue, I attempted the following:

```toml
add_newline = true
format = "$all$line_break"

[line_break]
disabled = false
```

But this also made no difference. I can verify that the other elements in my TOML file are not interferring, because when I comment them all out and just leave the above options the behavior is identical (the specific prompt contents just change a little bit.

**Comment by Advait-M** [comment]
> @Advait-M The vast majority of my `starship.toml` is just disabling a bunch of output that I don't want to see, along with custom symbols using a nerd font for some of the formatting for other sub-commands. If you remove all of that, it boils down to just this:
> 
> ```toml
> [line_break]
> disabled = true
> ```
> 
> `add_newline` is `true` by default, and I didn't override that (plus I would expect this to have no impact either way, because it has to do with adding newlines _before_ the prompt, not after it). However, before filing this issue, I attempted the following:
> 
> ```toml
> add_newline = true
> format = "$all$line_break"
> 
> [line_break]
> disabled = false
> ```
> 
> But this also made no difference. I can verify that the other elements in my TOML file are not interferring, because when I comment them all out and just leave the above options the behavior is identical (the specific prompt contents just change a little bit).

Thanks for the info! Got it - agreed re `add_newline`. Yep, so `line_break` affects this:

Default state - just `$all` (or with `line_break` set to `disabled = false`): 
<img width="541" alt="image" src="https://github.com/warpdotdev/Warp/assets/12927474/8dd20cdc-e7f4-4954-90d1-c7e24ed42dcd">

`$all` with `line_break` set to `disabled = true`:
<img width="542" alt="image" src="https://github.com/warpdotdev/Warp/assets/12927474/01dbcff0-9d8c-4fae-8505-99935613d540">

I believe the top version is what you desire for a 2 line prompt? Let me know if I'm wrong here (with regards to the goal state) or I missed something!

**Comment by onecrayon** [comment]
@Advait-M Found it! Apparently if you disable the `character` module, then it doesn't matter if your `line_break` module is enabled or not; it will never output a linebreak. I'm not too sure what is going on there since those two should be inter-related based on their documentation, but this looks like something that deserves to be filed in the Starship issues rather than here.

**Comment by Advait-M** [comment]
> @Advait-M Found it! Apparently if you disable the `character` module, then it doesn't matter if your `line_break` module is enabled or not; it will never output a linebreak. I'm not too sure what is going on there since those two should be inter-related based on their documentation, but this looks like something that deserves to be filed in the Starship issues rather than here.

Ooh interesting - yeah that does sound weird, I wouldn't expect those two to be interconnected 🤔 .

Gotcha - agreed! Thanks for digging into this!

And again, thanks for raising this! I'll explore how to make the onboarding block that we show to Warp users better for Starship users on Bash too - want to make sure we can make it as easy as possible to go back to the previous experience, if users would like to! 😄

**Comment by Advait-M** [comment]
^ We're gonna try to improve the SLP onboarding block to specifically detect/target plugins such as Starship and p10k hence the re-open above! 😄

**Comment by Advait-M** [comment]
Starship-specific SLP onboarding block for Bash has been updated to this:

![image](https://github.com/warpdotdev/Warp/assets/12927474/98aad1bc-db96-4408-99e6-f3ac3454fcc7)

Closing out this issue 😄 !

**Comment by Integralist** [comment]
Hmm, the solution of `[line_break]` doesn't work for me 😞 

Below a condensed version of my Starship config. 

Can someone who has the old 2-line prompt behaviour working help me understand what I need to be configuring. Thanks!

```toml
command_timeout = 5000

format = """\
[](bg:#282A36 fg:#7DF9AA)\
[$jobs](bg:#7DF9AA fg:#282A36)\
[](fg:#7DF9AA bg:#1C3A5E)\
$time\
[](fg:#1C3A5E bg:#3B76F0)\
$directory\
[](fg:#3B76F0 bg:#FCF392)\
$git_branch\
[](fg:#FCF392 bg:#f0af22)\
$git_status\
$git_metrics\
[](fg:#f0af22 bg:#bd4024)\
$custom\
[](fg:#bd4024 bg:#ff8a9f)\
$golang\
$lua\
$nodejs\
$perl\
$php\
$python\
$ruby\
$rust\
$shell\
$terraform\
$zig\
[](fg:#ff8a9f bg:#282A36)\
$character\
$cmd_duration\
$line_break\
"""

add_newline = true

[line_break]
disabled = false

[character]
success_symbol = '[ ➜](bold green) '
error_symbol = '[ ✗](#E84D44) '
```

**Comment by Advait-M** [comment]
@Integralist hmm, that's weird yep; I would've expected that config to show up with a 2-line prompt 🤔 (was messing around with this myself)

To check - are you on Zsh or Bash or Fish? On Zsh/Fish, you can also add a newline at the rcfile level (as opposed to the Starship toml level). Though, I'm guessing this is likely Bash?

**Comment by Advait-M** [comment]
> I'm using Zsh actually how do you do this at the RC level?

Oh nice - could you try adding this to the end of your rcfile `PROMPT="${PROMPT}"$'\n'` 👀 - this should work for that prompt!

**Comment by jhegele** [comment]
Any idea how to fix this with fish? The `[line_break]` fix isn't working for me either. Thanks!

**Comment by Advait-M** [comment]
> Any idea how to fix this with fish? The `[line_break]` fix isn't working for me either. Thanks!

For fish, you should be able to use the following (add it to end of `config.fish`) @jhegele :

`functions --copy fish_prompt fish_prompt_orig; function fish_prompt; fish_prompt_orig; echo; end`

**Comment by jhegele** [comment]
No luck. Also tried swapping out `fish_prompt` for `fish_right_prompt` (I'm using both) and that doesn't seem to work either. I'm using Warp + Starship + fish if that makes any difference. Appreciate the help @Advait-M!

**Comment by Advait-M** [comment]
By the way @Integralist and @jhegele - did the both of you try the command you got when updating Warp to the latest version in the SLP onboarding block? Wanted to confirm the triggering logic is working correctly for folks

For Zsh:

![image](https://github.com/user-attachments/assets/233a0547-2b07-4014-a98f-62b4eca7db06)

For Fish:

![image](https://github.com/user-attachments/assets/006258c8-caac-4dd3-846b-557edbc019e8)

**Comment by Integralist** [comment]
Apologies I've not been able to check yet. Will do so on Monday and report back either way. Thanks again

**Comment by jhegele** [comment]
> > No luck. Also tried swapping out `fish_prompt` for `fish_right_prompt` (I'm using both) and that doesn't seem to work either. I'm using Warp + Starship + fish if that makes any difference. Appreciate the help @Advait-M!
> 
> Hmm... could you also provide your `starship.toml`? Want to figure out why that isn't working - for me with fish and that line in rcfile: ![image](https://private-user-images.githubusercontent.com/12927474/348356074-e3833117-99bc-4267-9e7d-e86a16d148a2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA4MTUwMzQsIm5iZiI6MTcyMDgxNDczNCwicGF0aCI6Ii8xMjkyNzQ3NC8zNDgzNTYwNzQtZTM4MzMxMTctOTliYy00MjY3LTllN2QtZTg2YTE2ZDE0OGEyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzEyVDIwMDUzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI4YzBlZTIwYjk1MDIzOGNlM2RjYzlhNDE5OWRiYTA1YTYzOGRlYThlYWEyMzgyNTg4YmU2OTBiNjM0M2VhNjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.cRcXTROEb-wHyZIcebOg4svIIR8dSKb7NAuKIaHYydI)

@Advait-M starship.toml is below, nothing particularly weird in there as far as I'm aware. I didn't notice the prompt to run that command when I updated Warp. 🤦

```toml
format = """
$directory\
$git_branch\
$git_status\
$fill\
$python\
$c\
$elixir\
$elm\
$golang\
$haskell\
$java\
$julia\
$nodejs\
$nim\
$rust\
$scala\
$docker_context\
"""

# Disable the blank line at the start of the prompt
# add_newline = false

# Set longer command timeout for nodenv
command_timeout = 1000

add_newline = true

# You can also replace your username with a neat symbol like  to save some space
[fill]
symbol = " "

[directory]
# style = "fg:#DA627D"
style = "cyan bold"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[python]
pyenv_version_name = true
style = "fg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[c]
symbol = " "
style = "fg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[docker_context]
symbol = " "
style = "fg:#06969A"
format = '[ $symbol $context ]($style) $path'

[elixir]
symbol = " "
style = "fg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[elm]
symbol = " "
style = "fg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[git_branch]
symbol = ""
style = "fg:#FCA17D"
format = '[ $symbol $branch ]($style)'

[git_status]
style = "fg:#FCA17D"
format = '[$all_status$ahead_behind ]($style)'

[golang]
symbol = " "
style = "fg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[haskell]
symbol = " "
style = "fg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[java]
symbol = " "
style = "fg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[julia]
symbol = " "
style = "fg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[nodejs]
symbol = ""
style = "fg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[nim]
symbol = " "
style = "fg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[rust]
symbol = ""
style = "fg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[scala]
symbol = " "
style = "fg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[time]
disabled = false
time_format = "%R"           # Hour:Minute Format
style = "fg:#33658A"
format = '[ $time ]($style)'

[line_break]
disabled = false

```
