### ISSUE TITLE
Brighten bold text feature from iTerm2

### ISSUE THREAD

**Issue by zalishchuk** [warpdotdev/Warp#5566]
### Dupe Check

- [X] I have [searched Warp feature requests](https://github.com/warpdotdev/warp/issues?q=is%3Aissue+label%3A%22Feature+requests%22) and there are no duplicates

### Describe the solution you'd like?

High-contrast colors for the bold text that were presented in iTerm2 and I liked them a lot. Right now my solution is to swap `normal` and `bright` colors in my custom theme I converted from iTerm2, but all non-bold colors are "dimmed", so simply swapping colors don't give a correct result I want to achieve with Warp.

**iTerm2:**
<img width="512" alt="image" src="https://github.com/user-attachments/assets/185a1237-64ab-4811-b52c-5887aaedea3e" />

**Warp:**
<img width="512" alt="image" src="https://github.com/user-attachments/assets/9d8bfda8-e583-439d-a9a4-d8871437b5f9" />

**Theme:**
```yaml
accent: '#c7c7c7'
background: '#000000'
foreground: '#cccccc'
details: 'darker'
terminal_colors:
  normal:
    black: '#686868'
    red: '#FF6E67'
    green: '#5EFA67'
    yellow: '#FEFC68'
    blue: '#6970FF'
    magenta: '#FF76FF'
    cyan: '#60FDFF'
    white: '#FFFfff'
  bright:
    black: '#000000'
    red: '#CA1A00'
    green: '#00C301'
    yellow: '#C7C500'
    blue: '#0325C8'
    magenta: '#CA30C7'
    cyan: '#00C5C7'
    white: '#C7C7C7'

```

### How important is this feature to you?

3

### Warp Internal (ignore) - linear-label:39cc6478-1249-4ee7-950b-c428edfeecd1

None
