### ISSUE TITLE
Failed to deserialize AI response YAML: unexpected character: ``' at line 1 column 1

### ISSUE THREAD

**Issue by liuxuan30** [warpdotdev/Warp#5808]
### Dupe Check

- [x] I have [searched Warp bugs](https://github.com/warpdotdev/warp/issues?q=is%3Aissue+label%3ABugs) and there are no duplicates

### Describe the bug

I'm sorry, I couldn't complete that request.

Failed to deserialize AI response YAML: unexpected character: ``' at line 1 column 1
Raw response:
```yaml
response:
    thought_and_action:
        thought: |
            The previous command lists the network services, but doesn't provide statistics. I'll try to find more information using `system_profiler`.
        action:
            run_command:
                command: |
                    system_profiler SPNetworkDataType
                is_read_only: true
citations: []
```

### To reproduce

 choose gemini 2.0 flash, trigger agent mode by cmd + I
enter: get macos network extensions stats
wait for it

### Expected behavior

execute command and analyze

### Screenshots

//workspace gemini 2.0 flash
get macos network extensions stats
I need to find a command that can display the statistics for macOS network extensions. I'll start by searching for a command-line tool that provides this functionality.
I'm sorry, I couldn't complete that request.

Failed to deserialize AI response YAML: unexpected character: ``' at line 1 column 1
Raw response:
```yaml
response:
    thought_and_action:
        thought: |
            The previous command lists the network services, but doesn't provide statistics. I'll try to find more information using `system_profiler`.
        action:
            run_command:
                command: |
                    system_profiler SPNetworkDataType
                is_read_only: true
citations: []
```

### Operating system

MacOS

### Operating system and version

15.3.0

### Current Warp version

v0.2025.02.05.08.02.stable_03

### Regression

No, this bug or issue has existed throughout my experience using Warp

### Does this block you from using Warp daily?

No

### Is this an issue only in Warp?

Yes, I confirmed that this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b9d78064-c89e-4973-b153-5178a31ee54e

None
