### ISSUE TITLE
Bug Report: AI Feature Fails with YAML Deserialization Error

### ISSUE THREAD

**Issue by Albrz** [warpdotdev/Warp#5837]
### Pre-submit Checks

- [x] I have [searched Warp bugs](https://github.com/warpdotdev/warp/issues?q=is%3Aissue+label%3ABugs) and there are no duplicates
- [x] I have [searched Warp known issues page](https://docs.warp.dev/help/known-issues) and my issue is not there

### Describe the bug

When using the "Agent Mode" in Warp Terminal and making multiple queries in quick succession, I frequently encounter an error that prevents the request from being completed. The error message displayed is:

I'm sorry, I couldn't complete that request.
Failed to deserialize AI response YAML: mapping values are not allowed in this context at line 7 column 181
response:
    thought_and_action:

This issue occurs after using the "Agent Mode" several times in sequence. It disrupts the workflow and causes the AI to become unreliable, especially for extended use.

Steps to Reproduce:

Open Warp Terminal and activate the "Agent Mode."
Make multiple queries in sequence to the AI feature.
Observe that, after several interactions, the error appears instead of a response.
Expected Behavior:
The AI should respond correctly to all queries without failing due to YAML deserialization issues, even after multiple interactions in "Agent Mode."

System Information:

Warp Terminal version: v0.2025.02.12.16.51.stable_03
OS: Ubuntu 22.04.5 LTS - Kernel 6.8.0-52-generic
Additional Context:
Let me know if you need any logs or additional details to help diagnose the issue.

Thanks!

### To reproduce

Using the "Agent Mode" in Warp Terminal and making multiple queries in quick succession,

### Expected behavior

Using the "Agent Mode" in Warp Terminal and making multiple queries in quick succession,

### Operating system

MacOS

### Operating system and version

22.04

### Current Warp version

v0.2025.02.12.16.51.stable_03

### Regression

No, this bug or issue has existed throughout my experience using Warp

### Does this block you from using Warp daily?

Yes, this issue prevents me from using Warp daily.

### Is this an issue only in Warp?

Yes, I confirmed that this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b9d78064-c89e-4973-b153-5178a31ee54e

None

**Comment by qazi0** [comment]
Ran into the same error, whilst in Agent mode (CMD + I) on M1 Pro MBP (MacOS 15.3.1), Warp v0.2025.02.19.08.02.stable_05

<img width="1663" alt="Image" src="https://github.com/user-attachments/assets/31edff16-475e-4383-9e93-4fd45cdb0d6b" />

The prompt that caused it:

```shell
I need to schedule a meeting with 5 people across different time zones.
- Alice is in New York (EDT) and available 9am-5pm local time
- Bob is in London (GMT) and available 10am-6pm local time
- Charlie is in Tokyo (JST) and available 8am-3pm local time
- David is in San Francisco (PDT) and available 8am-4pm local time
- Eve is in Sydney (AEST) and available 9am-4pm local time

Find all possible meeting times when everyone can attend, expressed in each person's local time.
```
The attached output is for claude haiku 3.5, but I got the same error with gemini-flash-2.0 and once for gpt-4o (it worked on the second attempt)

It looks like a YAML formatting error in the response returned by the model, somwhere around this section
```yaml
response:
    thought_and_action:
        thought: |
            I'll create a Python script to calculate the overlapping time slots across these different time zones. 
            This requires converting each person's local available times to a common time zone and finding the intersection.
        action:
            code:
                files:
                    - meeting_scheduler.py
                query: |
                    Write a Python script that:
                    1. Defines time zones for each person
                    2. Converts their local available times to UTC
                    3. Finds the overlapping time slots
                    4. Converts the overlapping slots back to each person's local time
citations: []
```

[Here](https://stackoverflow.com/a/56612181) is a solution at SO of the same error. Probably the system prompt needs to be edited to ensure YAML correctness of the response.

Here is the errored response on the same prompt from gemini-flash-2.0:

====
I'm sorry, I couldn't complete that request.

Failed to deserialize AI response YAML: unexpected character: ``' at line 1 column 1
Raw response:
```yaml
response:
    answer:
        answer: |
            Finding a time that works for everyone across these time zones requires converting all availabilities to a common time zone (UTC is often easiest) and then converting back to each local time. This can be complex, and would likely be best handled by a dedicated scheduling tool or calendar application that understands time zones.

            However, I can outline the approach to solve this manually:

            1.  **Convert all availabilities to UTC:**
                *   Alice (New York, EDT = UTC-4): 9am-5pm EDT is 13:00-21:00 UTC
                *   Bob (London, GMT = UTC+0): 10am-6pm GMT is 10:00-18:00 UTC
                *   Charlie (Tokyo, JST = UTC+9): 8am-3pm JST is 23:00 (previous day) - 06:00 UTC
                *   David (San Francisco, PDT = UTC-7): 8am-4pm PDT is 15:00-23:00 UTC
                *   Eve (Sydney, AEST = UTC+10): 9am-4pm AEST is 23:00 (previous day) - 06:00 UTC

            2.  **Find the overlapping time in UTC:**
                *   Overlapping time needs to satisfy all the individual's availability
                *   Consider that Charlie and Eve's availability spans two days in UTC.
                *   The intersection of these times is between 15:00 UTC and 18:00 UTC

            3.  **Convert the overlapping time back to each local time zone:**
                *   Alice (New York, EDT = UTC-4): 11am-2pm EDT
                *   Bob (London, GMT = UTC+0): 3pm-6pm GMT
                *   Charlie (Tokyo, JST = UTC+9): Midnight - 3am JST (next day)
                *   David (San Francisco, PDT = UTC-7): 8am-11am PDT
                *   Eve (Sydney, AEST = UTC+10): 1am-4am AEST (next day)

            Therefore, a possible meeting time that works for everyone is 15:00-18:00 UTC, which corresponds to the local times listed above.

            Keep in mind that this assumes that Daylight Saving Time (DST) is in effect for all locations, given the "EDT", "PDT" and "AEST" designators. If DST is not in effect, the time zone offsets will be different and the calculations will need to be adjusted.
```
====
