### ISSUE TITLE
Unable to Launch SSH Session via Warp on Windows

### ISSUE THREAD

**Issue by thejjw** [warpdotdev/Warp#6583]
### Pre-submit Checks

- [x] I have [searched Warp bugs](https://github.com/warpdotdev/warp/issues?q=is%3Aissue+label%3ABugs) and there are no duplicates
- [x] I have [searched Warp known issues page](https://docs.warp.dev/help/known-issues) and my issue is not there
- [ ] I have included the logs (optional, but helps expedite the bug fix). [Log gathering intructions](https://docs.warp.dev/support-and-billing/sending-us-feedback#gathering-warp-logs)

### Describe the bug

Hello,
I cannot get warp terminal to properly add ssh launch configuration file..and warp terminal isn’t helping me debug why.
I installed warp using winget on windows.
I read [Launch Configurations | Warp documentation](https://docs.warp.dev/terminal/sessions/launch-configurations) to write my configuration, which is like below:
```
name: "SSH to user@host:port"
windows:
  - tabs:
      - title: "SSH to user@host:port" 
        layout:
          cwd: ""
          panes:
              commands:
                - exec: ssh.exe -p port user@host
```
Of course user , port, host are filled appropriately in actual file
When I click plus icon and choose new configuration it opens something but it turns out to be a generic powershell console, not ssh I was hoping for.
Warp isn’t telling me what or why its doing that.
Could someone help me fix the situation?
Thanks.

### To reproduce

```
name: "SSH to user@host:port"
windows:
  - tabs:
      - title: "SSH to user@host:port" 
        layout:
          cwd: ""
          panes:
              commands:
                - exec: ssh.exe -p port user@host
```

### Screenshots, videos, and logs

![Image](https://github.com/user-attachments/assets/3bd5ba25-1474-4bdc-8752-c3491aa1b19d)

### Operating system (OS)

Windows

### Operating system and version

windows 11 24h2

### Regression

No, this bug or issue has existed throughout my experience using Warp

### Does this block you from using Warp daily?

Yes, this issue prevents me from using Warp daily.

### Is this an issue only in Warp?

Yes, I confirmed that this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b9d78064-c89e-4973-b153-5178a31ee54e

None
