### ISSUE TITLE
Workflow options or default arguments

### ISSUE THREAD

**Issue by vgarvardt** [warpdotdev/Warp#997]
### Describe the solution you'd like?

Workflows are really great idea - already migrated almost all my code snippets from notes. But one feature is missing for me - predefined options for an argument.

E.g., I have several snippets like this:

```yaml
---
name: AWS SSO Login <profile-name>
command: "aws sso login --profile <profile-name>"
tags: [aws, sso]
description: "Login to AWS <profile-name>"
arguments: []
```

with around 10 predefined profiles. Currently I can either create 10 workflows, or define profile name as an argument, but then I need to remember all of them and type them manually. Yes, autocomplete will help me the second time, but anyway free-type input does not make any sense in this case.

It would be great to have `arguments.options` field with the list of pre-defined values that will be available when selecting a workflow, so for the example above it will be something like

```yaml
---
name: AWS SSO Login
command: "aws sso login --profile {{profile-name}}"
tags: [aws, sso]
description: "Login to AWS profile"
arguments:
  - name: profile-name
    description: AWS profile name
    options: [ foo, bar, baz ]
```

This is just one of the examples, I have several commands like this with limited list of arguments that are currently duplicated as several workflows with predefined commands for every possible input.

**Comment by horbo** [comment]
Yes! I would even expand options value to contain labels too, like:

```yaml
---
name: AWS SSO Login
command: "aws sso login --profile {{profile-name}}"
tags: [aws, sso]
description: "Login to AWS profile"
arguments:
  - name: profile-name
    description: AWS profile name
    options:
      - label: label1
        value: value1
      - label: label2
        value: value2 
```

It would be helpful for UUID-like values.
